---
title: 'CA2124: encapsular cláusulas finalmente vulneráveis em tentativa externa'
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- CA2124
- WrapVulnerableFinallyClausesInOuterTry
helpviewer_keywords:
- CA2124
- WrapVulnerableFinallyClausesInOuterTry
ms.assetid: 82efd224-9e60-4b88-a0f5-dfabcc49a254
author: jillre
ms.author: jillfra
manager: jillfra
ms.workload:
- multiple
ms.openlocfilehash: 09c79aae178cdbd0fff79aa454b577a40aae3faf
ms.sourcegitcommit: a8e8f4bd5d508da34bbe9f2d4d9fa94da0539de0
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 10/19/2019
ms.locfileid: "72624613"
---
# <a name="ca2124-wrap-vulnerable-finally-clauses-in-outer-try"></a>CA2124: encapsular cláusulas finalmente vulneráveis em tentativa externa

|||
|-|-|
|NomeDoTipo|WrapVulnerableFinallyClausesInOuterTry|
|CheckId|CA2124|
|Categoria|Microsoft.Security|
|Alteração significativa|Sem interrupção|

## <a name="cause"></a>Causa
Nas versões 1,0 e 1,1 do .NET Framework, um método público ou protegido contém um `try` / `catch` / bloco de `finally`. O bloco `finally` parece redefinir o estado de segurança e não está incluído em um bloco `finally`.

> [!NOTE]
> Esta regra herdada não está disponível nos analisadores do FxCop. Para obter mais informações, consulte [regras preteridas](fxcop-rule-port-status.md#deprecated-rules).

## <a name="rule-description"></a>Descrição da regra
Essa regra localiza `try` / blocos de `finally` no código que tem como destino as versões 1,0 e 1,1 do .NET Framework que podem estar vulneráveis a filtros de exceção mal-intencionada presentes na pilha de chamadas. Se operações confidenciais, como a representação ocorrerem no bloco try, e uma exceção for gerada, o filtro poderá ser executado antes do bloco `finally`. Para o exemplo de representação, isso significa que o filtro seria executado como o usuário representado. Atualmente, os filtros são implementados somente em Visual Basic.

> [!NOTE]
> Nas versões 2,0 e posteriores do .NET Framework, o tempo de execução protege automaticamente um `try` / `catch` /  `finally` bloqueio de filtros de exceção mal-intencionados, se a redefinição ocorrer diretamente dentro do método que contém o bloco de exceção.

## <a name="how-to-fix-violations"></a>Como corrigir violações
Coloque o `try` desencapsulado / `finally` em um bloco try externo. Consulte o segundo exemplo a seguir. Isso força o `finally` a ser executado antes do código de filtro.

## <a name="when-to-suppress-warnings"></a>Quando suprimir avisos
Não suprima um aviso nessa regra.

## <a name="pseudo-code-example"></a>Exemplo de pseudo-código

### <a name="description"></a>Descrição

O pseudocódigo a seguir ilustra o padrão detectado por essa regra.

```csharp
try {
   // Do some work.
   Impersonator imp = new Impersonator("John Doe");
   imp.AddToCreditCardBalance(100);
}
finally {
   // Reset security state.
   imp.Revert();
}
```

O pseudocódigo a seguir mostra o padrão que você pode usar para proteger seu código e atender a essa regra.

```csharp
try {
     try {
        // Do some work.
     }
     finally {
        // Reset security state.
     }
}
catch()
{
    throw;
}
```
